# 8004表示注册到zookeeper服务器的支付服务提供者端口号
server:
  port: 8004

# 服务别名--注册zookeeper到注册中心名称
# zk的节点为临时节点，连接失败后自动删除，重新启动注册后又生成新的流水号
spring:
  application:
    name: cloud-provider-payment
  cloud:
    zookeeper:
      connect-string: 192.168.1.4:2181

