server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com #eureka服务端的实例名称，集群部署时，不可重名（localhost），此处为hosts文件中配置的本地地址
  client:
    # false表示不向注册中心注册自己。（不向自己注册自己）
    register-with-eureka: false
    # false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      # 单机就是自己
      #defaultZone: http://eureka7002.com:7002/eureka/
      # 集群指向其它eureka
      defaultZone: http://eureka7001.com:7001/eureka/
