server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称（localhost）
  client:
    # false表示不向注册中心注册自己。（不向自己注册自己）
    register-with-eureka: false
    # alse表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ # 单机配置
      # 单机就是7001自己
      defaultZone: http://eureka7001.com:7001/eureka/
      # 集群指向其它eureka，把自己注册进其他的服务节点中，多个使用逗号分隔
      #defaultZone: http://eureka7002.com:7002/eureka/
    #server:
      # 关闭自我保护机制，保证不可用服务被及时踢除【默认是开启的】
      #enable-self-preservation: false
      # 心跳发送时间间隔【单位：ms】
      #eviction-interval-timer-in-ms: 2000